name: BUILD_FINAL_V56

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install Core 2.4.2
        run: |
          arduino-cli config init
          arduino-cli config set board_manager.additional_urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core update-index
          arduino-cli core install esp8266:esp8266@2.4.2

      - name: Compile
        run: |
          mkdir build_dir
          cp GMpro2_V82.ino build_dir/build_dir.ino
          arduino-cli compile --fqbn esp8266:esp8266:generic build_dir --output-dir ./output

      - name: Get Binary
        uses: actions/upload-artifact@v4
        with:
          name: GMpro2_Final_v56
          path: ./output/*.bin
